# LUCAS THESIS

Information on updates

**Objective**: Here we bring together code to obtain the union data that will be the input to his analyses.

**Description**: The goal is to loop through all possible unions in a given list and calculate (1) the weighted average returns, and (2) the feasibility scores according to (a) discrimination, (b) trade, and (c) political dimensions.

In [1]:
#Print time
from datetime import date, datetime
today = date.today()
datetoday = today.strftime("%d%B%Y")
print("Today's date:", datetoday)
begin = datetime.now()
print(begin)

#Importing packages
import numpy as np
import pandas as pd
import pickle
import os
import site
import sys
import matplotlib.pyplot as plt
import seaborn as sns
from google.oauth2 import service_account
from google.cloud import bigquery 
import itertools
import random 

#Set the working directory 
def setdropbox(account='personal'):
    """
    To be directed to PRINZ account, put 'business' instead of 'personal'
    """
    import os
    from pathlib import Path
    import json
    try:
        json_path = (Path(os.getenv('LOCALAPPDATA'))/'Dropbox'/'info.json').resolve()
    except FileNotFoundError:
        json_path = (Path(os.getenv('APPDATA'))/'Dropbox'/'info.json').resolve()
    with open(str(json_path)) as f:
        j = json.load(f)
    personal_dbox_path = Path(j[account]['path'])
    print(personal_dbox_path)
    os.chdir(personal_dbox_path)

#Load custom functions in gnome_helper
setdropbox()
os.chdir("prank/code")
from  gnome_helper import *


#Set paths
data = "C:/Users/u0080222/Dropbox (Personal)/Desktop/FEASPOL/data/"
results = "C:/Users/u0080222/Dropbox (Personal)/Desktop/FEASPOL/results/explore/"
fromwatson = 'C:/Users/u0080222/PRINZteam Dropbox/Dennis Verhoeven/patbis2021/data/fromWATSON/'
frompatstat=  'C:/Users/u0080222/PRINZteam Dropbox/Dennis Verhoeven/patbis2021/data/fromPATSTAT/'

#Set files

#Country lists
eu = ['BE', 'BG',	'CZ',	'DK',	'DE',	'EE',	'IE',	'SE',	'ES',	
      'FR', 'GR',	'HR',	'IT',	'CY',	'LV',	'LT',	'LU',	'HU',	
      'MT', 'NL',	'AT',	'PL',	'PT',	'RO',	'SI',	'SK',	'FI']
oecd_cn = ['AU', 'AT', 'BE', 'CA', 'CL', 'CZ', 'DK',	'DE', 'EE', 'FI', 'FR', 'GR', 
        'HU', 'IS', 'IE', 'IL', 'IT', 'JP', 'KR', 'LV', 'LT', 'LU', 'MX', 'NL',	
        'NZ', 'NO', 'PL', 'PT', 'SK', 'SI', 'ES', 'SE', 'CH', 'TR', 'US',
         'GB','CN'] #UK as UK and GB; Greece as GR (EL does not occur)
supra = ['eu','euplusuk','oecd','g7']
# Make list of unique countries
countries = list(set(oecd_cn+eu+supra))
#period string
yrs = "2009_2018"

Today's date: 23April2024
2024-04-23 23:02:55.231651
C:\Users\u0080222\Dropbox (Personal)

## Load data

In [1]:
import numpy as np
import pandas as pd
import pickle
import os
import site
import sys
import matplotlib.pyplot as plt
import seaborn as sns
import itertools
import random 
data = "C:/Users/lucas/Thesis/data/"
result = "C:/Users/lucas/Thesis/results"
#Load the dataframes of the returns and the size of the countries
retmat = pd.read_csv(data+"retmat.csv")
sizemat = pd.read_csv(data+"sizemat.csv")

In [52]:
for l in list(retmat.ctry_code.drop_duplicates()):
    print(l,end='-')

..-00-04-63-75-92-A -AB-AD-AE-AF-AG-AI-AL-AM-AN-AO-AP-AQ-AR-AS-AT-AU-AW-AX-AZ-BA-BB-BC-BD-BE-BF-BG-BH-BI-BJ-BK-BL-BM-BN-BO-BQ-BR-BS-BT-BU-BV-BW-BX-BY-BZ-C -CA-CC-CD-CF-CG-CH-CI-CJ-CK-CL-CM-CN-CO-CR-CS-CT-CU-CV-CW-CX-CY-CZ-DA-DD-DE-DJ-DK-DM-DO-DU-DW-DZ-EA-EC-EE-EG-EH-EM-EN-EP-ER-ES-ET-EU-F -F1-FI-FJ-FK-FL-FM-FN-FO-FR-FU-FW-FX-GA-GB-GC-GD-GE-GF-GG-GH-GI-GJ-GL-GM-GN-GP-GQ-GR-GS-GT-GU-GW-GY-HA-HB-HE-HI-HK-HN-HR-HS-HT-HU-IB-ID-IE-IL-IM-IN-IO-IQ-IR-IS-IT-JA-JE-JM-JO-JP-JR-JS-JT-J[-KA-KE-KG-KH-KI-KM-KN-KP-KR-KS-KW-KY-KZ-LA-LB-LC-LE-LI-LK-LN-LR-LS-LT-LU-LV-LX-LY-MA-MB-MC-MD-ME-MG-MH-MI-MK-ML-MM-MN-MO-MP-MQ-MR-MS-MT-MU-MV-MW-MX-MY-MZ-N -N;-NB-NC-NE-NF-NG-NH-NI-NJ-NK-NL-NM-NO-NP-NR-NS-NU-NV-NY-NZ-OA-OH-OM-ON-OR-OS-OT-OU-OX-PA-PE-PF-PG-PH-PI-PK-PL-PM-PN-PO-PR-PS-PT-PW-PY-QA-QC-QL-QQ-RE-RF-RI-RJ-RO-RS-RU-RW-SA-SB-SC-SD-SE-SG-SH-SI-SJ-SK-SL-SM-SN-SO-SP-SR-SS-ST-SU-SV-SW-SX-SY-SZ-T -TB-TC-TD-TE-TF-TG-TH-TI-TJ-TK-TM-TN-TO-TP-TR-TS-TT-TU-TV-TW-TX-TY-TZ-UA-UC-UD-UE-UG-UK-UM-UN-UR-US-UT-UW-UX-UY-UZ-VA-VC-VE-VG-VI-VN-VT-VU-VZ-WA-WF-WI-WO-WS-XK-XP-YE-YR-YS-YU-ZA-ZJ-ZM-ZW-ZZ-

In [2]:
retmat

,Unnamed: 0,ctry_code,catid,catname,istrax_global,istrax_to_CN,istrax_to_AT,istrax_to_GB,istrax_to_euplusuk,istrax_to_CA,...,istrax_to_DK,istrax_to_IS,istrax_to_CH,istrax_to_PT,istrax_to_CL,istrax_to_LT,istrax_to_ES,istrax_to_HR,istrax_to_oecd,istrax_to_EE
0,0,..,1,"Electrical machinery, apparatus, energy",0.000000,0.000000,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
1,1,..,14,Pharmaceuticals,0.000000,0.000000,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
2,2,..,26,Textile and paper machines,0.000000,0.000000,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
3,3,00,2,Audio-visual technology,0.000000,0.000000,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
4,4,00,4,Computer technology,0.000000,0.000000,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7975,7975,ZW,38,Aerospace,0.000000,0.000000,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
7976,7976,ZW,41,Clean,0.107941,0.000000,0.0,0.0,0.004531,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.079754,0.0
7977,7977,ZZ,1,"Electrical machinery, apparatus, energy",0.326801,0.326801,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
7978,7978,ZZ,40,Clean Cars,0.326801,0.326801,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
7979,7979,ZZ,41,Clean,0.326801,0.326801,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0

Make a dataframe with the sum of number of innovations across fields for each country. Also, show a table with how many innovations by country in descending order, giving us an idea of how many of the world's innovations are in any country list we define.

In [10]:
all_countrysize = sizemat.groupby('ctry_code')[['innocount']].sum().sort_values('innocount', ascending=False)
all_countrysize['cumsum'] = all_countrysize['innocount'].cumsum()
total_innovations = all_countrysize['innocount'].sum()
filtered_sizemat = sizemat[sizemat['ctry_code'].isin(country_list)]
filtered_countrysize = filtered_sizemat.groupby('ctry_code')[['innocount']].sum().sort_values('innocount', ascending=False)
filtered_countrysize['cumsum'] = filtered_countrysize['innocount'].cumsum()
filtered_countrysize['cumratio'] = filtered_countrysize['cumsum'] / total_innovations

display(filtered_countrysize.reset_index().head(20))

   ctry_code  innocount    cumsum  cumratio
0         US    3127113   3127113  0.193980
1         JP    2859762   5986875  0.371375
2         CN    2349747   8336622  0.517134
3         KR    2276047  10612669  0.658321
4         DE    1212751  11825420  0.733550
5         FR     428156  12253576  0.760109
6         GB     320073  12573649  0.779963
7         CA     238337  12811986  0.794748
8         CH     196902  13008888  0.806962
9         NL     172187  13181075  0.817643
10        IT     140236  13321311  0.826342
11        SE     115253  13436564  0.833491
12        ES     106224  13542788  0.840081
13        IL      94566  13637354  0.845947
14        AU      91995  13729349  0.851653
15        AT      87920  13817269  0.857107
16        PL      82359  13899628  0.862216
17        FI      72534  13972162  0.866715
18        BE      71109  14043271  0.871126
19        DK      50676  14093947  0.874270

See Figure 1

## Define functions

#### calcunion()

Calculate the subsidy scheme and coherent returns for a union

In [2]:
#calculate the subsidy scheme and coherent returns of a union 
def calcunion(union, fracfield=0.1, fractot=0.01, retmat=retmat, sizemat=sizemat):  
    # restrict matrix
    toflowlist = ['istrax_global']
    for c in union:
        toflowlist.append('istrax_to_'+c)
    ids = ['ctry_code','catid','catname'] 
    rets = retmat[retmat['ctry_code'].isin(union)][ids+toflowlist].copy()

    # add patent counts by field
    rets = pd.merge(rets, sizemat, on=ids)
    # total number of innovations union (this is full-counted, meaning there are double counts)
    innocounttot = rets['innocount'].sum()
    rets['innocountunion'] = innocounttot

    # sum up the destination countries to get returns to union as a whole
    toflowlist = []
    for c in union:
        toflowlist.append('istrax_to_'+c)
    rets['istrax_union'] = rets[toflowlist].sum(axis=1)

    ### Make the union policy (sub-dataframe with all fields that are chosen)
    # sort field-countries by decreasing union returns
    rets = rets.sort_values(by='istrax_union', ascending=False) #Istrax is the marginal return to subsidies in a given field of innovation
    # Make cumulative sum of innocount, to showcase how many innovations are integrated
    rets['cumsum'] = rets['innocount'].cumsum()
    rets['subsidized_field'] = round(rets['innocount'] * fracfield)
    rets['subsidized_total'] = round(rets['subsidized_field'].cumsum(), 0)
    rets['total_to_subsidize'] = round(innocounttot * fractot, 0)
    rets['to_be_subsidized'] = rets['total_to_subsidize'] - rets['subsidized_total']
    rets.loc[rets['to_be_subsidized'] < 0, 'subsidized_field'] = rets['subsidized_field'] + rets['to_be_subsidized']
    rets.loc[rets['to_be_subsidized'] < 0, 'to_be_subsidized'] = 0
    
   # Filter out rows where subsidized_field is greater than 0
    rets = rets[rets['subsidized_field'] > 0]
    unionpol = rets.copy()
    
    # Extract innovation counts per country and store them in a dictionary
    country_innovation_counts = {}
    for country_code in union:
        country_data = rets[rets['ctry_code'] == country_code]
        innovation_count = country_data['subsidized_field'].sum()
        country_innovation_counts[country_code] = innovation_count

    # Calculate weighted sum
    weighted_sum = (unionpol['istrax_union'] * unionpol['subsidized_field']).sum()
    weighted_avg = weighted_sum / unionpol['subsidized_field'].sum()

    return unionpol, weighted_avg, country_innovation_counts

#### calc_weights_union()

Calculate the fraction of the total subsidies to a country following a union policy

In [3]:
def calc_weights_union(union, country_innovation_counts): 
    total_innovation_count_union = sum(country_innovation_counts.values())
    weights_union = {}
    for country, count in country_innovation_counts.items():
        if country in union:
            weights_union[country] = count / total_innovation_count_union
    return weights_union

#### calc_weights_individual()

Calculate the fraction of the total subsidies to a country following a national policy

In [4]:
def calc_weights_individual(union):
    
    countrysize = sizemat.groupby('ctry_code')[['innocount']].sum().sort_values('innocount',ascending=False).reset_index()
    unioncountrysize = countrysize[countrysize['ctry_code'].isin(union)].copy()
    unioncountrysize['sum']=unioncountrysize['innocount'].sum()
    unioncountrysize['equalw'] = unioncountrysize['innocount']/unioncountrysize['sum']
    weights_individual = unioncountrysize.set_index('ctry_code')['equalw'].to_dict()
    return weights_individual

#### gini()

Calculate the Inequality dimension, comparing the wiehts in a union with the weight in a national policy

In [5]:
def calc_gini(weights_individual, weights_union):
    # Create DataFrame from dics.
    colnames = ['country', 'share without union', 'share with union']
    df = pd.DataFrame({'share without union':weights_individual, 'share with union':weights_union})

    # Sort the DataFrame by 'share with union' in ascending order. This assures that the cumulative share with union is always smaller or equal to the share without union
    df = df.sort_values(['share with union','share without union'], ascending=True)

    # Calculate cumulative shares
    df['cumulative share without union'] = df['share without union'].cumsum()
    df['cumulative share with union'] = df['share with union'].cumsum()
    
    # Calculate surfaces under both cumulative shares.
    df['surfwithout'] = df['cumulative share without union']*df['share without union']
    df['surfwith'] = df['cumulative share with union']*df['share without union']

    # Subtract the surface of the share with union from the share without union
    if df['surfwithout'].sum()>0:
        gini =  round((df['surfwithout'].sum() - df['surfwith'].sum())/df['surfwithout'].sum(),4)
    else:
        gini = 0
    return gini

#### create_trade_matrix()

The Trade flows are quantified and conglomerated in a country-piars trade matrix

In [8]:
def create_trade_matrix(country_list):
    # Create an empty DataFrame to store the matrix
    matrix = pd.DataFrame(index=country_list, columns=country_list)
    
    directory =  "C:/Users/lucas/Thesis/data/Export"
    total_trade = {}
    iso_file_path = os.path.join(directory, 'ISO.xlsx')
    iso_codes_df = pd.read_excel(iso_file_path)

    for country_code in country_list:
        file_path = os.path.join(directory, f'Export_{country_code}.xlsx')
        if os.path.exists(file_path):
            Export = pd.read_excel(file_path)
            Export['ISO 3'] = Export['ISO 3'].str.upper()
            # Merge with iso_codes_df to convert Alpha-3 to Alpha-2 codes
            df_merged = pd.merge(Export, iso_codes_df[['Alpha-2', 'ISO 3']], how='inner', on='ISO 3')
            total_trade[country_code] = df_merged['Trade Value'].sum()
            filtered_df = df_merged[df_merged['Alpha-2'].isin(country_list)]
    
            # Update the matrix with the export data
            for index, row in filtered_df.iterrows():
                source_country = country_code
                destination_country = row['Alpha-2']
                trade_value = row['Trade Value']
                matrix.loc[source_country, destination_country] = trade_value
    
    # Fill NaN values with 0
    matrix.fillna(0, inplace=True)
    for country in country_list:
        matrix.loc[country] /= total_trade[country]
    for col in matrix.columns:
        if col in matrix.index:
            matrix.loc[col, col] = 1
    return matrix

#### create_geopol_matrix()

Starting from the identified IGO's specific to our country set, the country-pair Geopolitical allignement is quantified

In [9]:
def create_geopol_matrix(country_list):
    #created the Geopolitical matrix, from the IGO table in word
    from collections import defaultdict

    rows = [
        ['AU', 'NZ', 'US'],
        ['CA', 'DK', 'FI', 'IS', 'NO', 'SE', 'US'],
        ['AU', 'AT', 'BE', 'BG', 'CN', 'HR', 'CY', 'CZ', 'DK', 'EE', 'FI', 'FR', 'DE', 'GR', 'HU', 'IE', 'IT', 'JP', 'KR', 'LV', 'LT', 'LU', 'MT', 'NL', 'NZ', 'NO', 'PL', 'PT', 'RO', 'SK', 'SI', 'ES', 'SE', 'CH', 'GB'],
        ['AU', 'AT', 'BE', 'CA', 'CN', 'DK', 'FI', 'FR', 'DE', 'IE', 'IT', 'JP', 'LU', 'NL', 'NO', 'PT', 'KR', 'ES', 'SE', 'SI', 'GB', 'US'],
        ['CN', 'JP', 'KR', 'TR'],
        ['AU', 'CN', 'JP', 'NZ', 'KR'],
        ['AU', 'CA', 'CL', 'CN', 'JP', 'KR', 'MX', 'NZ', 'US'],
        ['AU', 'AT', 'BE', 'BG', 'CA', 'CL', 'CN', 'HR', 'CZ', 'DK', 'EE', 'FI', 'FR', 'DE', 'GR', 'IS', 'IE', 'IL', 'IT', 'JP', 'KR', 'LV', 'LT', 'LU', 'MX', 'NL', 'NZ', 'NO', 'PL', 'PT', 'RO', 'SK', 'SI', 'ES', 'SE', 'CH', 'TR', 'GB', 'US'],
        ['BE', 'NL', 'LU'],
        ['AU', 'CA', 'CL', 'CH', 'NL', 'KR', 'GB'],
        ['BE', 'FR', 'DE', 'NL', 'CH'],
        ['AT', 'BE', 'BG', 'HR', 'CZ', 'DK', 'EE', 'FI', 'FR', 'DE', 'GR', 'HU', 'IE', 'IT', 'LV', 'LT', 'LU', 'NL', 'NO', 'PL', 'PT', 'RO', 'SK', 'SI', 'ES', 'SE', 'CH', 'GB'],
        ['AU', 'CA', 'MT', 'NZ', 'GB'],
        ['AT', 'BE', 'BG', 'HR', 'CY', 'CZ', 'DK', 'EE', 'FI', 'FR', 'DE', 'GR', 'HU', 'IS', 'IE', 'IT', 'LV', 'LT', 'LU', 'MT', 'NL', 'NO', 'PL', 'PT', 'RO', 'SK', 'SI', 'ES', 'SE', 'CH', 'TR', 'GB'],
        ['DK', 'EE', 'FI', 'DE', 'IS', 'LV', 'LT', 'NO', 'PL', 'SE'],
        ['AT', 'BG', 'HU', 'DE', 'RO', 'SK', 'HR'],
        ['IS', 'NO', 'CH'],
        ['AT', 'BE', 'BG', 'CZ', 'DK', 'FI', 'FR', 'DE', 'GR', 'HU', 'IL', 'IT', 'NL', 'NO', 'PL', 'PT', 'RO', 'SK', 'ES', 'SE', 'CH', 'GB'],
        ['AT', 'BE', 'CZ', 'DK', 'FI', 'FR', 'DE', 'IE', 'IT', 'NL', 'PL', 'PT', 'ES', 'SE', 'CH', 'GB'],
        ['AT', 'BE', 'CZ', 'DK', 'EE', 'FI', 'FR', 'DE', 'GR', 'HU', 'IE', 'IT', 'LU', 'NL', 'NO', 'PL', 'PT', 'RO', 'ES', 'SE', 'CH', 'GB'],
        ['AT', 'BE', 'BG', 'HR', 'CY', 'CZ', 'DK', 'EE', 'FI', 'FR', 'DE', 'GR', 'HU', 'IS', 'IE', 'IT', 'LV', 'LT', 'LU', 'MT', 'NL', 'NO', 'PL', 'PT', 'RO', 'SK', 'SI', 'ES', 'SE', 'CH', 'TR'],
        ['CL', 'MX'],
        ['CL', 'MX', 'US'],
        ['CN', 'CY', 'KR'],
        ['AT', 'BE', 'BG', 'HR', 'CY', 'CZ', 'DK', 'EE', 'FI', 'FR', 'DE', 'GR', 'HU', 'IE', 'IT', 'LV', 'LT', 'LU', 'MT', 'NL', 'PL', 'PT', 'RO', 'SK', 'SI', 'ES', 'SE', 'JP', 'NO', 'CH', 'GB'],
        ['CL', 'MX', 'IL', 'AT', 'BE', 'BG', 'CY', 'CZ', 'HR', 'FR', 'DE', 'HU', 'LU', 'NL', 'PT', 'RO', 'SK', 'SI', 'ES', 'CH', 'SE', 'TR', 'GB', 'GR', 'IT', 'MT', 'NO'],
        ['MX', 'CL'],
        ['CL', 'FR', 'IT', 'MX', 'PT', 'ES'],
        ['CY', 'FR', 'GR', 'IL', 'IT', 'MT', 'PT', 'ES', 'TR'],
        ['BE', 'CA', 'EE', 'IT', 'JP', 'SE', 'US'],
        ['DK', 'FI', 'IE', 'NO', 'SE'],
        ['CA', 'MX', 'US'],
        ['BE', 'BG', 'CA', 'HR', 'CZ', 'DE', 'DK', 'EE', 'FI', 'FR', 'GR', 'GB', 'HU', 'IS', 'IT', 'LV', 'LT', 'LU', 'NL', 'NO', 'PL', 'PT', 'RO', 'SK', 'SI', 'SE', 'ES', 'TR', 'GB', 'US'],
        ['CL', 'ES', 'MX', 'PT'],
        ['BE', 'DK', 'FI', 'FR', 'DE', 'IS', 'IE', 'LU', 'NL', 'NO', 'PT', 'ES', 'SE', 'CH', 'GB'],
        ['AU', 'AT', 'BE', 'CA', 'CL', 'CZ', 'DK', 'DE', 'EE', 'FI', 'FR', 'GR', 'HU', 'IS', 'IE', 'IL', 'IT', 'JP', 'KR', 'LV', 'LT', 'LU', 'MX', 'NL', 'NZ', 'NO', 'PL', 'PT', 'SK', 'SI', 'ES', 'SE', 'CH', 'TR', 'US', 'GB'],
        ['CA', 'CL', 'MX', 'US'],
        ['AT', 'BE', 'BG', 'CA', 'HR', 'CY', 'CZ', 'DK', 'EE', 'FI', 'FR', 'DE', 'GR', 'HU', 'IS', 'IE', 'IT', 'LV', 'LT', 'LU', 'MT', 'NL', 'NO', 'PL', 'PT', 'RO', 'SK', 'SI', 'ES', 'SE', 'CH', 'TR', 'GB', 'US'],
        ['CA', 'CL', 'MX', 'PT', 'ES', 'US']
    ]

    pair_counts = defaultdict(int)
    for row in rows:
        unique_pairs = set()
        for i in range(len(row)):
            for j in range(i + 1, len(row)):
                unique_pairs.add(tuple(sorted([row[i], row[j]])))
        # Increment count for each pair
        for pair in unique_pairs:
            pair_counts[pair] += 1
            
    list_length = len(rows)
    unique_countries = sorted(set(country for sublist in rows for country in sublist))
    matrix_df = pd.DataFrame(index=unique_countries, columns=unique_countries)

    # Fill the DataFrame with counts for specific pairs divided by the length of the list, to get the percentage
    for country1 in unique_countries:
        for country2 in unique_countries:
            if country1 != country2:
                pair = tuple(sorted([country1, country2]))
                matrix_df.loc[country1, country2] = pair_counts[pair] / list_length
            else:
                matrix_df.loc[country1, country2] = 1
    matrix_df = matrix_df.loc[country_list,country_list].copy()
    print("succesfull")
    return matrix_df

#### cut_matrix()

In [10]:
def cut_matrix(matrix,country_list):
    """
    matrix should have country codes as index and columns. The function will then cut the matrix so we only have those in country_list
    """
    cutmat = matrix.copy()
    cutmat = cutmat.loc[country_list,country_list]
    return cutmat

#### genF()

Transform the country-pair matrices to specific union feasibility scores

In [11]:
def genF(similarity_matrix):
    mat = similarity_matrix.copy()
    #Size of matrix is the number of rows of the dataframe times the number of columns:
    NN=mat.shape[0]**2
    #Multiply all elements of the df with (1/NN)
    mat = mat*(1/NN)
    #Sum up all elements (first over rows, then over columns)
    F = mat.sum().sum()
    return F

#### generate_country_combinations()

Out of the country list, every possible union is formed

In [12]:
def generate_country_combinations(country_list):
    """
    Generate all possible combinations of countries from the input list.
    """
    country_combinations = []
    for country in range(1, len(country_list) + 1):
        for combination in itertools.combinations(country_list, country):
            country_combinations.append(list(combination))
    return country_combinations

## Preparation

In [8]:
country_list = ['AT', 'AU', 'BE', 'CA', 'CH', 'CN', 'DE', 'DK', 'ES', 'FI', 'FR', 'GB', 'IL', 'IT', 'JP', 'KR', 'NL', 'PL', 'SE', 'US']
country_list = sorted(country_list)

In [14]:
#Make the overall trade matrix
trade_matrix = create_trade_matrix(country_list)

In [15]:
#Make the overall geopolitical matrix
geopol_matrix = create_geopol_matrix(country_list)

succesfull

## Make output dataframes with unions and their scores

In [17]:
#First, make list of combinations 
unionlist = generate_country_combinations(country_list)
chunksize = 500
chunk = 0
mine = 0
for counter, union in enumerate(unionlist[0:200000]):
    firstofchunk=False
    if counter%chunksize == 0 :
        chunk+=1
        firstofchunk = True
        if (os.path.exists(results + "hasbegun" + str(chunk)+".pkl")==False):
            mine = 1
            hasbegunfile = pd.DataFrame(columns=["empty"])
            hasbegunfile.to_pickle(results+"hasbegun"+str(chunk)+".pkl")
            #print("start of new chunk")
    if mine==1:
        if firstofchunk:
            #Make empty dataframe 
            columns = ['union','weighted_average_returns','gini','Ft','Fg']
            dfout = pd.DataFrame(columns=columns)
        #Get weighted returns and weights of innovation subsidized in union
        unionpol, weighted_avgret, country_innovation_counts = calcunion(union, fracfield=0.1, fractot=0.01, retmat=retmat, sizemat=sizemat)
        weights_union=calc_weights_union(union, country_innovation_counts)
        #Get individual weights absent any union
        weights_individual = calc_weights_individual(union)
        #Calculate gini 
        gini = calc_gini(weights_individual, weights_union)
        #Cut the trade matrix to get relevant similarity matrix
        cutmattrade = cut_matrix(trade_matrix,union)
        #Cut the geopolitical matrix to get relevant similarity matrix
        cutmatgeopol = cut_matrix(geopol_matrix,union)
        #Based on similarity matrix, generate trade F (Ft) 
        Ft = genF(cutmattrade)
        #Based on similarity matrix, generate geopolitical F (Fg) 
        Fg = genF(cutmatgeopol)
        dfout.loc[counter]=[union,weighted_avgret,gini,Ft,Fg]
        #We print the output once in a while
        r = random.randint(1, 1000)
        #if r==5:
            #print(union,weighted_avgret,gini,Ft,Fg)
        if (counter+1)%chunksize==0:
            #Make file
            dfout.to_pickle(results+"out"+str(chunk)+".pkl")
            print(chunk, end="-")
            mine = 0

46-47-48-49-50-52-54-56-58-60-62-64-66-68-70-72-74-76-78-80-82-84-86-89-93-100-108-117-128-139-150-161-172-183-194-205-216-227-238-249-260-271-282-293-304-315-326-337-348-359-370-381-392-

In [ ]:
raise

## Bring dataframes together in 1 result dataframe with all unions

In [20]:
dflist=[]
chunk=0
for counter, union in enumerate(unionlist):
    if counter%chunksize == 0 :
        chunk+=1
        try:
            dflist.append(pd.read_pickle(results+"out"+str(chunk)+".pkl"))
        except:
            print("no such file: ", results+"out"+str(chunk)+".pkl")
result = pd.concat(dflist)
result

no such file:  C:/Users/u0080222/Dropbox (Personal)/Desktop/FEASPOL/results/explore/out31.pkl
no such file:  C:/Users/u0080222/Dropbox (Personal)/Desktop/FEASPOL/results/explore/out32.pkl
no such file:  C:/Users/u0080222/Dropbox (Personal)/Desktop/FEASPOL/results/explore/out45.pkl

,union,weighted_average_returns,gini,Ft,Fg
0,[BE],0.033555,0.0000,1.000000,1.000000
1,[BG],0.024290,0.0000,1.000000,1.000000
2,[CY],0.017660,0.0000,1.000000,1.000000
3,[CZ],0.050796,0.0000,1.000000,1.000000
4,[DE],0.214632,0.0000,1.000000,1.000000
...,...,...,...,...,...
199995,"[BG, CY, FR, GR, IT, LT, LU, MT]",0.118420,0.0418,0.144816,0.320513
199996,"[BG, CY, FR, GR, IT, LT, LU, NL]",0.130619,0.0629,0.148761,0.349359
199997,"[BG, CY, FR, GR, IT, LT, LU, SE]",0.148887,0.0180,0.144763,0.349359
199998,"[BG, CY, FR, GR, IT, LT, LV, MT]",0.117670,0.0250,0.147005,0.311699
199999,"[BG, CY, FR, GR, IT, LT, LV, NL]",0.129606,0.0650,0.150386,0.337340

In [ ]:
raise

## Working with the results

In [ ]:
results = "C:/Users/lucas/Thesis/results/"
df = pd.read_pickle(results+"country_unions_top20.pkl")

### Calculations with the results

In [ ]:
#adapt the Gini coefficient and make the composite score
df.loc[df['gini']<0, 'gini']= -df['gini']
df['gini'] = 1 - df['gini']
weight = 3 
df['composite_score'] = (df['gini'] + df['Ft'] + df['Fg']) / weight 
#create a dataframe without singels
df_nosingle = df.iloc[20:]
df_nosingle

In [ ]:
#add the country codes individually to the dataframe
def dflist_to_columns(df,listcol,colname="c"):
    adf = df.copy()
    # Expanding the lists into separate columns
    max_length = df[listcol].apply(len).max()  # Find the maximum length of any list
    for i in range(max_length):
        adf[colname+str(i+1)] = df[listcol].apply(lambda x: x[i] if len(x) > i else None)

    adf['size'] = adf[listcol].apply(len)
    return adf

def list_to_dummies(df,listcol):
    adf = df[[listcol]].reset_index().rename(columns={'index':'id'})
    #function to make a row for each list element
    exploded_df = adf.explode(listcol)
    # Creating dummy variables for each country code
    dummies = pd.get_dummies(exploded_df[listcol])
    adf = adf.join(dummies.groupby(exploded_df.index).sum())

    return adf
    
df_processed = dflist_to_columns(df, 'union')
df_processed = pd.concat([df_processed, list_to_dummies(df_processed, 'union')], axis=1)
df_processed

In [ ]:
#add the Feasibility Bins to the data frame, based on the composite score
bin_ranges = [0, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 1]
bin_labels = ['Bin 1', 'Bin 2', 'Bin 3', 'Bin 4', 'Bin 5', 'Bin 6', 'Bin 7', 'Bin 8']
bins = pd.cut(df['composite_score'], bins=bin_ranges, labels=bin_labels, right=True)
df['Bins'] = bins
df_processed['Bins'] = bins

### Corrleation matrix

In [ ]:
#make the correlation matrix
columns_of_interest = ['weighted_average_returns', 'gini', 'Ft', 'Fg', 'composite_score', 'size']
selected_df = df_processed[columns_of_interest]

#Compute the correlation matrix
correlation_matrix = selected_df.corr()
correlation_matrix

See Table 3

### Scatter plots

In [ ]:
#For Trade Feasibility
plt.figure(figsize=(10, 6))
sns.scatterplot(data= df_nosingle, x = 'Ft', y ='weighted_average_returns', color='purple')
sns.regplot(data=df_nosingle, x = 'Ft', y = 'weighted_average_returns', scatter=False, color='blue', order=1)

plt.title('Scatter Plot Trade with Regression Line')
plt.ylabel('Weighted Average Returns')
plt.xlabel('Trade Feasibility (Ft)')
plt.show()

See Figure 7

### Return the top unions for every Bin

In [ ]:
#Get thighest returning unions for every Bin
def top_unions_per_bin(df): 
    top_unions_list = []
    for bin_label in df['Bins'].unique():
        bin_df = df[df['Bins'] == bin_label]
        sorted_bin_df = bin_df.sort_values(by='weighted_average_returns', ascending=False)    
        top_5_unions = sorted_bin_df.head(5)    
        top_unions_list.append(top_5_unions[['Bins', 'union', 'weighted_average_returns', 'composite_score']])
    top_unions_df = pd.concat(top_unions_list, ignore_index=True)
    top_unions_df.set_index('Bins', inplace=True)
    top_unions_df = top_unions_df.sort_values(by='weighted_average_returns', ascending=False)
    
    return top_unions_df
top = top_unions_per_bin(df)

See Table 8

### Return the best unions for every individual country

In [ ]:
def best_unions_per_country(df_processed, countries_of_interest, bin_labales)
    best_unions_per_country = []
    for country in countries_of_interest:
        country_df = df_processed[df_processed[country] == 1]
        for bin_label in bin_labels:
            bin_country_df = country_df[country_df['Bins'] == bin_label]
            if bin_country_df.empty:
                continue
            best_union = bin_country_df.loc[bin_country_df['weighted_average_returns'].idxmax()]
            
            # Store the relevant information for this country-bin combination
            best_unions_per_country.append({
                'Country': country,
                'Bin': bin_label,
                'Best Union': best_union['union'],
                'Weighted Average Returns': best_union['weighted_average_returns']
            })
    # Convert the list of dictionaries to a DataFrame
    best_unions_df = pd.DataFrame(best_unions_per_country)
    best_unions_df = best_unions_df.sort_values(by='Bin')
    return best_unions_df

best_unions_all = best_unions(df_processed, country_list, bin_labels)
US_excluded = df_processed[df_processed['US'] != 1]
best_unions_us = best_unions(US_excluded, country_list, bin_labels)

See Table 9 and 10

### Comparing to national policy

In [ ]:
def calcunion_national(union, retmat = retmat):
    df_list = []
    for country in union:
        # Assuming calcunion(country) returns a tuple of dataframes and other values
        all_df, _, _ = calcunion([country])
        ids = ['ctry_code', 'catid', 'catname']
        all_df = all_df[ids +[ 'istrax_global','subsidized_field']].copy()
        
        merged_df = pd.merge(all_df, retmat, on = ids)
        lijst = ['subsidized_field']
        lijst2 = []
        for land in cl:
            lijst.append('istrax_to_' + land)
            lijst2.append('istrax_to_' + land)
        merged_df = merged_df[ids + lijst]
        merged_df['istrax_to_union'] = merged_df[lijst2].sum(axis = 1) 
        df_list.append(merged_df)
    
    national_df = pd.concat(df_list)

    weighted_sum = (national_df['istrax_to_union'] *  national_df['subsidized_field']).sum()
    weighted_avg = weighted_sum / national_df['subsidized_field'].sum()

    return national_df, weighted_avg


def calculate_weighted_avg_returns_national(df, countries):
    data = []
    for c in countries:
        # Filter DataFrame for specific country
        country_df = df[df['ctry_code'] == c]
        
        weighted_sum = (df['istrax_to_' + c] * df['subsidized_field']).sum()
        sum_subsidized = country_df['subsidized_field'].sum()
        weighted_avg = weighted_sum / df['subsidized_field'].sum()
        data.append([c, weighted_avg, sum_subsidized])
    result_df = pd.DataFrame(data, columns=['Country', 'Weighted_Avg_Return', 'Subsidies_Received'])
    
    return result_df

national, avg_national = calcunion_national(country_list)
data = []
for c in cl1:
    national_df = national[national['ctry_code'] == c]
    sum_subsidies = national_df['subsidized_field'].sum()
    data.append([c, sum_subsidies])
result_df = pd.DataFrame(data, columns=['Country', 'Subsidies_Received'])
all_df, _,_ = calcunion(country_list)
result_vertical = calculate_weighted_avg_returns(all_df, country_list)
merged_result = pd.concat([result_vertical, result_df], axis=1)
merged_result

## Testing Calculation time

In [ ]:
%%time
#How big is a list of 27 countries?
unionlist = generate_country_combinations(eu)
import sys
sizelist = sys.getsizeof(unionlist)
print(sizelist/1000000, "Mb")
len(unionlist)

In [ ]:
%%time
#How big is a list of 20 countries?
c20 = ['BE', 'BG',	'CZ',	'DK',	'DE',	'EE',	'IE',	'SE',	'ES',	
      'FR', 'GR',	'HR',	'IT',	'CY',	'LV',	'LT',	'LU',	'HU',	
      'MT', 'NL']
unionlist = generate_country_combinations(c20)
import sys
sizelist = sys.getsizeof(unionlist)
print(sizelist/1000000, "Mb")
len(unionlist)

In [ ]:
%%time
#How big is a list of 25 countries?
c20 = ['BE', 'BG',	'CZ',	'DK',	'DE',	'EE',	'IE',	'SE',	'ES',	
      'FR', 'GR',	'HR',	'IT',	'CY',	'LV',	'LT',	'LU',	'HU',	
      'MT', 'NL','AT', 'PL', 'PT', 'RO', 'SI']
unionlist = generate_country_combinations(c20)
import sys
sizelist = sys.getsizeof(unionlist)
print(sizelist/1000000, "Mb")
len(unionlist)